# Generated by Django 4.2.9 on 2024-02-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admdatetime',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passdate',
        ),
    ]
